"""
Django settings for raiz project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os





# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1yqp4mb^j0uqm-uf6zgr+^axhif(n-^x%kk2y$folet5#i##!a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '3.222.245.142', 
    'localhost',
]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'software.apps.SoftwareConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'raiz.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'software.context_processors.modulos_sidebar',
                'software.context_processors.empresa_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'raiz.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'facsiswave',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',  # O la dirección IP de tu servidor MySQL
        'PORT': '3306',       # El puerto por defecto de MySQL es 3306
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-pe'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

STATICFILES_DIRS = [
    BASE_DIR / "static",
    "/var/www/static/",
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de la ruta media
MEDIA_URL = '/media/'  # URL que se usará para acceder a los archivos media
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Ruta en el sistema de archivos

# Configuración de correo Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'jerojasd@alumno.unsm.edu.pe'  # ← Cambia esto
EMAIL_HOST_PASSWORD = 'usrlkwexthgfjmxh'  # ← Contraseña de aplicación de Gmail
DEFAULT_FROM_EMAIL = 'MotoVentas <jerojasd@alumno.unsm.edu.pe>'

CSRF_TRUSTED_ORIGINS = [
    'https://misistemaventas.ngrok.app', # Añade el comodín HTTPS para ngrok
]

#Para encriptar 
ENCRYPTION_KEY = 'lhgnTN5ZgcS6UKinpZdMrknlCeUPFxy5Eq10e8tyB0I='

URL_ENCRYPTION_KEY = 'WT0j3asFkLJj7xaZFL7EtvJtyd8ELf1q1ju5DMwt6jY='

#Para consumir la API RENIC
TOKENPERU_TOKEN = 'sk_11701.nbA9F1Pyxxiq9B1tn2dGAzjtioUPEBoJ'

#TOKENPERU_DEMO_MODE = True
