# Generated by Django 5.2.6 on 2025-11-20 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_categoria_clientes_codigocorreo_compradetalle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacenes',
            fields=[
                ('id_almacen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_almacen', models.CharField(max_length=100)),
                ('codigo_almacen', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('capacidad_maxima', models.IntegerField(blank=True, null=True)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'almacenes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AperturaCierreCaja',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('saldo_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saldo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_apertura', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('hora_apertura', models.TimeField(blank=True, null=True)),
                ('hora_cierre', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'apertura_cierre_caja',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_caja', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_caja', models.IntegerField(blank=True, null=True)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'cajas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cilindrada',
            fields=[
                ('idcilindrada', models.AutoField(primary_key=True, serialize=False)),
                ('cilindrada_cc', models.CharField(max_length=255)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'cilindrada',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('numdoc', models.CharField(max_length=25, unique=True, verbose_name='Número de Documento')),
                ('razonsocial', models.CharField(max_length=255, verbose_name='Razón Social/Nombre Completo')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('estado', models.IntegerField(default=1, verbose_name='Estado')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono')),
                ('nombre_comercial_cliente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Comercial')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('idcolor', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecolor', models.CharField(max_length=50)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'color',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('idcredito', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_credito', models.CharField(max_length=50, unique=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_adelanto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_cuotas', models.IntegerField()),
                ('fecha_credito', models.DateTimeField(auto_now_add=True)),
                ('estado_credito', models.CharField(default='activo', max_length=20)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'creditos',
                'ordering': ['-fecha_credito'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id_cuota', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cuota', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tasa', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('interes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_adelanto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'cuotas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CuotasVenta',
            fields=[
                ('idcuotaventa', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cuota', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tasa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('interes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('monto_adelanto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_cuota', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('estado_pago', models.CharField(default='Pendiente', max_length=20)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'cuotasventa',
                'ordering': ['numero_cuota'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleTransferencia',
            fields=[
                ('id_detalle_transferencia', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='cantidad', default=1)),
                ('estado', models.IntegerField(db_column='estado', default=1)),
            ],
            options={
                'db_table': 'detalle_transferencia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id_distrito', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_distrito', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'distrito',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoProducto',
            fields=[
                ('idestadoproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreestadoproducto', models.CharField(max_length=50)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'estadoproducto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id_forma_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'formaspago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idmarca', models.AutoField(primary_key=True, serialize=False)),
                ('nombremarca', models.CharField(max_length=50)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'marca',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id_movimiento_caja', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], db_column='tipo_movimiento', max_length=10)),
                ('monto', models.DecimalField(db_column='monto', decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, db_column='fecha_movimiento')),
                ('estado', models.IntegerField(db_column='estado', default=1)),
                ('id_caja', models.ForeignKey(db_column='id_caja', on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos', to='software.caja')),
            ],
            options={
                'db_table': 'movimientos_caja',
                'ordering': ['-fecha_movimiento'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PagoCuota',
            fields=[
                ('idpagocuota', models.AutoField(primary_key=True, serialize=False)),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('numero_operacion', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField(default=1)),
                ('idcuotaventa', models.ForeignKey(db_column='idcuotaventa', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='software.cuotasventa')),
            ],
            options={
                'db_table': 'pagos_cuota',
                'ordering': ['-fecha_pago'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'password_reset_tokens',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idproveedor', models.AutoField(primary_key=True, serialize=False)),
                ('numdoc', models.CharField(max_length=255, unique=True, verbose_name='Número de Documento')),
                ('razonsocial', models.CharField(max_length=255, verbose_name='Razón Social/Nombre Completo')),
                ('estado', models.IntegerField(default=1, verbose_name='Estado')),
                ('nombre_comercial', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Comercial')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico')),
                ('departamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('provincia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia')),
                ('distrito', models.CharField(blank=True, max_length=100, null=True, verbose_name='Distrito')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'provincia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id_repuesto', models.AutoField(db_column='id_repuesto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=255)),
                ('estado', models.IntegerField(db_column='estado')),
                ('idcolor', models.ForeignKey(db_column='idcolor', on_delete=django.db.models.deletion.DO_NOTHING, related_name='repuestos', to='software.color')),
                ('idmarca', models.ForeignKey(db_column='idmarca', on_delete=django.db.models.deletion.DO_NOTHING, related_name='repuestos', to='software.marca')),
            ],
            options={
                'db_table': 'repuestos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RepuestoComp',
            fields=[
                ('id_repuesto_comprado', models.AutoField(db_column='id_repuesto_comprado', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('codigo_barras', models.CharField(max_length=100)),
                ('estado', models.IntegerField(db_column='estado')),
            ],
            options={
                'db_table': 'repuestoscomprado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Seriecomprobante',
            fields=[
                ('idseriecomprobante', models.AutoField(primary_key=True, serialize=False)),
                ('serie', models.CharField(max_length=4)),
                ('numero_actual', models.IntegerField(default=0)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'seriecomprobante',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_disponible', models.IntegerField(db_column='cantidad_disponible', default=0)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True, db_column='fecha_ultima_actualizacion')),
                ('estado', models.IntegerField(db_column='estado', default=1)),
                ('id_almacen', models.ForeignKey(db_column='id_almacen', on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='software.almacenes')),
            ],
            options={
                'db_table': 'stock',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sucursal', models.CharField(max_length=100)),
                ('codigo_sucursal', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_apertura', models.DateField()),
                ('estado', models.IntegerField(db_column='estado')),
                ('es_principal', models.BooleanField(db_column='es_principal', default=False)),
            ],
            options={
                'db_table': 'sucursales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipocomprobante',
            fields=[
                ('idtipocomprobante', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('abreviatura', models.CharField(max_length=255)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tipocomprobante',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id_tipo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'tipospago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id_transferencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_transferencia', models.DateField(db_column='fecha_transferencia')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, db_column='fecha_confirmacion', null=True)),
                ('numero_guia', models.CharField(blank=True, db_column='numero_guia', max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada')], db_column='estado', default='pendiente', max_length=20)),
            ],
            options={
                'db_table': 'transferencias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TwoFactorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('intentos', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'two_factor_codes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(db_column='id_vehiculo', primary_key=True, serialize=False)),
                ('imperfecciones', models.TextField(blank=True)),
                ('placas', models.TextField(blank=True)),
                ('serie_chasis', models.CharField(max_length=50)),
                ('serie_motor', models.CharField(max_length=50)),
                ('estado', models.IntegerField(db_column='estado')),
                ('idestadoproducto', models.ForeignKey(db_column='idestadoproducto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehiculos', to='software.estadoproducto')),
            ],
            options={
                'db_table': 'vehiculos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('idventa', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField(default=1)),
                ('idempresa', models.IntegerField(blank=True, null=True)),
                ('numero_comprobante', models.CharField(max_length=20)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('importe_recibido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vuelto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_ganancia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ventas',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='CodigoCorreo',
        ),
        migrations.DeleteModel(
            name='Distritos',
        ),
        migrations.DeleteModel(
            name='Lotes',
        ),
        migrations.DeleteModel(
            name='Modopago',
        ),
        migrations.DeleteModel(
            name='Numserie',
        ),
        migrations.DeleteModel(
            name='Proveedores',
        ),
        migrations.DeleteModel(
            name='Provincias',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='compradetalle',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='compras',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='departamentos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='detallecategoriaxunidades',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='detalletipousuarioxmodulos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombrecomercial'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='modulos',
            options={'managed': True, 'ordering': ['orden', 'nombremodulo']},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipocliente',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipoentidad',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipoigv',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipousuario',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='unidades',
            options={'managed': True, 'ordering': ['idunidad'], 'verbose_name': 'Unidad', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ventadetalle',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='aperturacierrecaja',
            name='idusuario',
            field=models.ForeignKey(blank=True, db_column='idusuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='software.usuario'),
        ),
        migrations.AddField(
            model_name='aperturacierrecaja',
            name='id_caja',
            field=models.ForeignKey(blank=True, db_column='id_caja', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='software.caja'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_tipo_entidad',
            field=models.ForeignKey(db_column='id_tipo_entidad', on_delete=django.db.models.deletion.DO_NOTHING, related_name='clientes', to='software.tipoentidad', verbose_name='Tipo de Entidad'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='idcompra',
            field=models.ForeignKey(blank=True, db_column='idcompra', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cuota', to='software.compras'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='idusuario',
            field=models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos_caja', to='software.usuario'),
        ),
        migrations.AddField(
            model_name='pagocuota',
            name='idusuario',
            field=models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to='software.usuario'),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='usuario',
            field=models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to='software.usuario'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='id_tipo_entidad',
            field=models.ForeignKey(db_column='id_tipo_entidad', on_delete=django.db.models.deletion.DO_NOTHING, related_name='proveedores', to='software.tipoentidad', verbose_name='Tipo de Entidad'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='id_provincia',
            field=models.ForeignKey(db_column='id_provincia', on_delete=django.db.models.deletion.DO_NOTHING, related_name='distritos', to='software.provincia'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='id_region',
            field=models.ForeignKey(db_column='id_region', on_delete=django.db.models.deletion.DO_NOTHING, related_name='provincias', to='software.region'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='idunidad',
            field=models.ForeignKey(db_column='idunidad', on_delete=django.db.models.deletion.DO_NOTHING, related_name='repuestos', to='software.unidades'),
        ),
        migrations.AddField(
            model_name='repuestocomp',
            name='id_repuesto',
            field=models.ForeignKey(db_column='id_repuesto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='repuestocomprados', to='software.repuesto'),
        ),
        migrations.AddField(
            model_name='detalletransferencia',
            name='id_repuesto_comprado',
            field=models.ForeignKey(blank=True, db_column='id_repuesto_comprado', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transferencias', to='software.repuestocomp'),
        ),
        migrations.AddField(
            model_name='stock',
            name='id_repuesto_comprado',
            field=models.ForeignKey(blank=True, db_column='id_repuesto_comprado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='software.repuestocomp'),
        ),
        migrations.AddField(
            model_name='sucursales',
            name='id_distrito',
            field=models.ForeignKey(db_column='id_distrito', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sucursales', to='software.distrito'),
        ),
        migrations.AddField(
            model_name='sucursales',
            name='idempresa',
            field=models.ForeignKey(db_column='idempresa', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sucursales', to='software.empresa'),
        ),
        migrations.AddField(
            model_name='caja',
            name='id_sucursal',
            field=models.ForeignKey(blank=True, db_column='id_sucursal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='software.sucursales'),
        ),
        migrations.AddField(
            model_name='almacenes',
            name='id_sucursal',
            field=models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.DO_NOTHING, related_name='almacenes', to='software.sucursales'),
        ),
        migrations.AddField(
            model_name='seriecomprobante',
            name='idtipocomprobante',
            field=models.ForeignKey(db_column='idtipocomprobante', on_delete=django.db.models.deletion.CASCADE, related_name='seriecomprobante', to='software.tipocomprobante'),
        ),
        migrations.AddField(
            model_name='pagocuota',
            name='id_tipo_pago',
            field=models.ForeignKey(db_column='id_tipo_pago', on_delete=django.db.models.deletion.CASCADE, to='software.tipopago'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='id_almacen_destino',
            field=models.ForeignKey(db_column='id_almacen_destino', on_delete=django.db.models.deletion.RESTRICT, related_name='transferencias_entrada', to='software.almacenes'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='id_almacen_origen',
            field=models.ForeignKey(db_column='id_almacen_origen', on_delete=django.db.models.deletion.RESTRICT, related_name='transferencias_salida', to='software.almacenes'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='idusuario_confirma',
            field=models.ForeignKey(blank=True, db_column='idusuario_confirma', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transferencias_confirmadas', to='software.usuario'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='idusuario_solicita',
            field=models.ForeignKey(db_column='idusuario_solicita', on_delete=django.db.models.deletion.RESTRICT, related_name='transferencias_solicitadas', to='software.usuario'),
        ),
        migrations.AddField(
            model_name='detalletransferencia',
            name='id_transferencia',
            field=models.ForeignKey(db_column='id_transferencia', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='software.transferencia'),
        ),
        migrations.AddField(
            model_name='twofactorcode',
            name='usuario',
            field=models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to='software.usuario'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='idproducto',
            field=models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='vehiculos', to='software.producto'),
        ),
        migrations.AddField(
            model_name='stock',
            name='id_vehiculo',
            field=models.ForeignKey(blank=True, db_column='id_vehiculo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='software.vehiculo'),
        ),
        migrations.AddField(
            model_name='detalletransferencia',
            name='id_vehiculo',
            field=models.ForeignKey(blank=True, db_column='id_vehiculo', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transferencias', to='software.vehiculo'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='id_almacen',
            field=models.ForeignKey(blank=True, db_column='id_almacen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='software.almacenes'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='id_caja',
            field=models.ForeignKey(blank=True, db_column='id_caja', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='software.caja'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='id_forma_pago',
            field=models.ForeignKey(db_column='id_forma_pago', on_delete=django.db.models.deletion.CASCADE, to='software.formapago'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='id_sucursal',
            field=models.ForeignKey(blank=True, db_column='id_sucursal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='software.sucursales'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='id_tipo_igv',
            field=models.ForeignKey(blank=True, db_column='id_tipo_igv', null=True, on_delete=django.db.models.deletion.CASCADE, to='software.tipoigv'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='id_tipo_pago',
            field=models.ForeignKey(blank=True, db_column='id_tipo_pago', null=True, on_delete=django.db.models.deletion.CASCADE, to='software.tipopago'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='idcliente',
            field=models.ForeignKey(db_column='idcliente', on_delete=django.db.models.deletion.CASCADE, to='software.cliente'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='idseriecomprobante',
            field=models.ForeignKey(db_column='idseriecomprobante', on_delete=django.db.models.deletion.CASCADE, to='software.seriecomprobante'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='idtipocomprobante',
            field=models.ForeignKey(db_column='idtipocomprobante', on_delete=django.db.models.deletion.CASCADE, to='software.tipocomprobante'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='idusuario',
            field=models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to='software.usuario'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='idventa',
            field=models.ForeignKey(blank=True, db_column='idventa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='software.ventas'),
        ),
        migrations.AddField(
            model_name='cuotasventa',
            name='idventa',
            field=models.ForeignKey(db_column='idventa', on_delete=django.db.models.deletion.CASCADE, to='software.ventas'),
        ),
        migrations.AddField(
            model_name='credito',
            name='idventa',
            field=models.OneToOneField(db_column='idventa', on_delete=django.db.models.deletion.CASCADE, related_name='credito', to='software.ventas'),
        ),
        migrations.AddIndex(
            model_name='repuesto',
            index=models.Index(fields=['nombre'], name='repuestos_nombre_4f63b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('id_almacen', 'id_repuesto_comprado'), ('id_almacen', 'id_vehiculo')},
        ),
    ]
